name: rm_flutter_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.1
  ferry: ^0.9.2
  gql_http_link: ^0.3.2
  ferry_flutter: ^0.3.2
  get_it: ^5.0.3
  flutter_slidable: ^0.5.7
  uuid: ^2.2.2
  rm_graphql_client:
    path: ../rm_graphql_client
  flutter:
    sdk: flutter
dev_dependencies:
  ferry_generator: ^0.3.3
  build_runner: ^1.10.2
  flutter_test: 
    sdk: flutter
flutter:
  uses-material-design: true
